### ISSUE TITLE
[백준] K - 카드 정렬하기

### ISSUE THREAD

**Issue by kihyuk-sung** [AlgorithmSqaud/Algorithm#2]
https://www.acmicpc.net/problem/1715

**Comment by tmdgusya** [comment]
https://github.com/AlgorithmSqaud/Algorithm/blob/main/Greedy_Alogorithm/Default/Roach.java

하나만 있을시 비교를 안해서 되도 0..

**Comment by tmdgusya** [comment]
K 교수님 강의 발췌록

1. 그리디로 풀수 있는지 확인해라 (배수, 혹은 최선의 선택이 답안이 되는 경우)
2. 안된다면 DP 다

**Comment by tmdgusya** [comment]
K 가 올려주신 LeetCode 문제 풀이본입니다.

https://github.com/AlgorithmSqaud/PersonalAlgorithm/tree/main/leetCode/122/roach

**Comment by sanhee** [comment]
백준 문제 풀이입니다.
https://github.com/AlgorithmSqaud/Algorithm/tree/main/Greedy_Alogorithm/Default/Noel 

Leet코드 예제는 좀이따가 이어서 업로드하겠습니다.
